name: Daily Tasks

on:
  schedule:
    # 对应北京时间 0:30（UTC+8）执行
    - cron: "30 16 * * *"  # UTC 时间 16:30 = 北京时间 0:30（次日）
  workflow_dispatch:

jobs:
  run-tasks:
    name: Run FF14 Risingstone Tasks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run FF14 Task
        continue-on-error: true  # 防止单次失败停止整个Job
        retry-on-error: true    # 自动重试3次（默认）
        
      - uses: docker://ghcr.io/starhearthunt/ff14risingstone_sign_task:master
        with:
          cookie: ${{ secrets.COOKIE }}
          user_agent: ${{ secrets.USER_AGENT }}
